openapi: 3.0.0

info:
  version: 3.0.0
  title: Fullfii API
  description: Used in the "Fullfii" IOS application
  termsOfService: https://fullfii.com/terms-of-service/

servers:
  - url: http://192.168.11.46:8080/api/v4/
    description: Development server
  - url: https://fullfii.com/api/v4/
    description: Production server

paths:
  /rooms:
    get:
      tags:
        - rooms
      summary: 20単位でroomを取得. クエリパラメータ"page"でページ指定.
      # description: Returns an array of User model
      parameters:
        - name: page
          in: query
          description: ページ（1からスタート）
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: A JSON array of Room model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
    post:
      tags:
        - rooms
      summary: roomを作成
      # description: Create a new User
      parameters: []
      requestBody:
        # description: user to create
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
                name:
                  type: string
                description:
                  type: string
                is_owner_speaker:
                  type: boolean
                is_exclude_different_gender:
                  type: boolean
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Room"
    delete:
      tags:
        - rooms
      summary: roomを削除
      description: 実際はDBからは削除せずis_activeをFalseにする。
      responses:
        "204":
          description: No Content
  /rooms/images:
    post:
      tags:
        - rooms
      summary: room imageをPOST
      parameters: []
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Room"
  /rooms/participants:
    post:
      tags:
        - rooms
      summary: roomへの参加
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                account_id:
                  type: string
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Room"
  /me/hidden-rooms:
    patch:
      tags:
        - me
      summary: roomの非表示
      parameters: []
      responses:
        "200":
          description: A JSON array of Me model
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Me"

components:
  schemas: # スキーマオブジェクトの定義
    Room:
      type: object
      properties:
        id:
          type: string
          example: c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
        name:
          type: string
          example: 人間関係の悩み聞いてほしい。
        description:
          type: string
          example: 職場の人間関係に関して悩みを持っています。聞いてくれる優しい方いますか？？
        image:
          type: string
          example: https://fullfii.com/media/profile_images/da3f2c91-6991-4a0f-99cc-89a39d33a734/avatar.jpg
        owner:
          type: object
          $ref: "#/components/schemas/Me"
        participants:
          type: array
          items:
            $ref: "#/components/schemas/Me"
        max_num_participants:
          type: integer
          example: 1
        is_owner_speaker:
          type: boolean
          example: true
        is_exclude_different_gender:
          type: boolean
          example: true
        created_at:
          type: string
          example: ""
        is_active:
          type: boolean
          example: true
    Me:
      type: object
      properties:
        id:
          type: string
          example: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
        name:
          type: string
          example: ひな
        gender:
          type: object
          $ref: "#/components/schemas/Gender"
        is_secret_gender:
          type: boolean
          example: true
        job:
          type: object
          $ref: "#/components/schemas/Job"
        introduction:
          type: string
          example: こんにちは。よろしくお願いいたします。
        num_of_thunks:
          type: integer
          example: 12
        date_joined:
          type: string
          example: ""
        image:
          type: string
          example: https://fullfii.com/media/profile_images/da3f2c91-6991-4a0f-99cc-89a39d33a734/avatar.jpg
        me:
          type: boolean
          example: true
        device_token:
          type: string
          example: dzhBOUWyPU21s-aiBZNPxP:APA91bG2vusYK8tSISPR15kipcrH5DIhBv5hfJmI4uGkVOyinkno1SJj_CBPxCAcXj95AUSOCzmOOZqUp7MvWWz25SxbwxAj4jVQq1W_lJM5SlZQzx_vWBW--2Fn0u4SmMulZsd5tngA
        is_active:
          type: boolean
          example: true
        hidden-rooms:
          type: array
          items:
            type: string
            example: b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11

    Gender:
      type: object
      properties:
        key:
          type: string
          example: female
        name:
          type: string
          example: FEMALE
        label:
          type: string
          example: 女性
    Job:
      type: object
      properties:
        key:
          type: string
          example: hs-student
        name:
          type: string
          example: HS_STUDENT
        label:
          type: string
          example: 高校生

tags:
  - name: rooms
    description: Access to Rooms
  - name: me
    description: Access to Me

externalDocs:
  description: App Store
  url: https://apps.apple.com/jp/app/fullfii/id1533306689
